### ISSUE TITLE
Знак градуса иногда меняется на знак вопроса в ромбе

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/home-automation-ui#62]
Периодически, когда приходит новая температура знак градуса меняется на знак вопроса в ромбе.
![2015-01-05 19 44 49](https://cloud.githubusercontent.com/assets/2894860/5616302/627cd46c-9514-11e4-92a4-1dae09f1b1b3.png)

**Comment by r3b-fish** [comment]
Не совсем понимаю причем тут фронтенд, данные приходят с сишного апи в JSapi, а дальше попадают в фронтенд уже через запросы. Я не контролирую scaleTitle, я на всякий случай привожу его к строчному виду примерно так String(binding.get('scaleTitle'))

**Comment by r3b-fish** [comment]
Баг найден в бэкэнде
